apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: flask-app
    template:
      metadata:
        labels:
          app: flask-app
      spec:
        containers:
        - name: flask-app
        #will be injected via jenkinsFile
          image: testcontainerregistrye83a3d39.azurecr.io/flask-app:latest
          ports:
          - containerPort: 5000
