FROM python

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

#Install system packages
RUN apt-get update && \
	apt-get install -y \
	build-essential \
	curl unzip \
	libyaml-dev \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

#Install Terraform
RUN curl -LO "https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip" && \
	unzip terraform_1.5.5_linux_amd64.zip && \
	mv terraform /usr/local/bin/ && \
	chmod +x /usr/local/bin/terraform && \
	rm terraform_1.5.5_linux_amd64.zip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 5000	

CMD ["python", "app.py"]
