---
- name: Configure AKS nodes
  hosts: azure_vm_group
  become: true
  
  tasks:
   - name: Install necessary tools on AKS nodes
     apt:
      name:
       - htop
       - curl
       - net-tools
      state: present

   - name: Set up environment variables
     copy:
        dest: /etc/environment
        content: |
         FLASK_ENV=production
---       
