---
- hosts: all
  become: true
  tasks: 
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service: 
        name: docker
        state: started
        enabled: true

    - name: Install Docker Python module
      pip: 
        name: docker
        state: present

    - name: Build Docker image for Flask app
      docker_image:
        path: ../python_app/app.py
        name: flask-app-image
        tag: latest
        
    #all the vars inputted below should be coming in via Jenkins
    - name: Log in to Azure Container Registry
      shell: az acr login --name "{{ acr_name }}"
      environment:
        AZURE_CLIENT_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        AZURE_SECRET: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
        AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT_ID') }}"

    - name: Pusher Docker image to ACR
      docker_image:
        name: flask-app-image
        tag: latest
        push: true
        repository: "{{ acr_name }}.azurecr.io/flask-app-image"
